; PlatformIO Project Configuration File

[platformio]
default_envs = federated_train_device_1

[common_esp32]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_speed = 115200
board_build.psram_type = octal
board_build.psram = true

[common_mqtt_demo]
extends = common_esp32
lib_deps =
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:auth_ecdh_once]
extends = common_esp32
monitor_port = COM6
build_src_filter = +<auth_ecdh/auth_ecdh.cpp>

[env:auth_ecdh_rekey]
extends = common_esp32
monitor_port = COM6
build_src_filter = +<auth_ecdh/try_auth.cpp>

[env:ecdh_handshake]
extends = common_esp32
monitor_port = COM6
build_src_filter = +<ecdh_handshake/ecdh.cpp>
lib_deps =
	bblanchon/ArduinoJson@^7.4.2
	fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:ecdh_handshake_speed]
extends = common_esp32
monitor_port = COM6
build_src_filter = +<ecdh_handshake_speed/ecdh_speed.cpp>
lib_deps =
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2
	fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:federated_train_device_1]
extends = common_esp32
build_src_filter = +<federated_train_device_1/1_federated_wifi_train.cpp>
build_flags =
	-D CONFIG_ARDUINO_LOOP_STACK_SIZE=32768
lib_deps = fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:federated_train_device_2]
extends = common_esp32
build_src_filter = +<federated_train_device_2/2_federated_wifi_train.cpp>
build_flags =
	-D CONFIG_ARDUINO_LOOP_STACK_SIZE=32768
lib_deps = fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:federated_train_device_3]
extends = common_esp32
build_src_filter = +<federated_train_device_3/3_federated_wifi_train.cpp>
build_flags =
	-D CONFIG_ARDUINO_LOOP_STACK_SIZE=32768
lib_deps = fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:federated_train_centr]
extends = common_esp32
build_src_filter = +<federated_train_centr/centr_federated_wifi_train.cpp>
build_flags =
	-D CONFIG_ARDUINO_LOOP_STACK_SIZE=32768
lib_deps = fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:aifes_init_dump]
extends = common_esp32
monitor_port = COM6
build_src_filter = +<aifes_init_dump/federated_test.cpp>
build_flags =
	-D CONFIG_ARDUINO_LOOP_STACK_SIZE=32768
lib_deps = fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:bench_flash_present]
extends = common_mqtt_demo
build_src_filter = +<benchmarks_flash/flash_present.cpp>

[env:bench_ram_present]
extends = common_mqtt_demo
build_src_filter = +<benchmarks_ram/ram_present.cpp>

[env:bench_speed_present]
extends = common_mqtt_demo
build_src_filter = +<benchmarks_speed/speed_present.cpp>

[env:bench_flash_simon]
extends = common_mqtt_demo
build_src_filter = +<benchmarks_flash/flash_simon.cpp>

[env:bench_ram_simon]
extends = common_mqtt_demo
build_src_filter = +<benchmarks_ram/ram_simon.cpp>

[env:bench_speed_simon]
extends = common_mqtt_demo
build_src_filter = +<benchmarks_speed/speed_simon.cpp>

[env:bench_speed_speck]
extends = common_mqtt_demo
build_src_filter = +<benchmarks_speed/speed_speck.cpp>

[env:bench_flash_speck]
extends = common_mqtt_demo
build_src_filter = +<benchmarks_flash/flash_speck.cpp>

[env:bench_ram_speck]
extends = common_mqtt_demo
build_src_filter = +<benchmarks_ram/ram_speck.cpp>
