; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-devkitc-1-n16r8v

[env:esp32-s3-devkitc-1-n16r8v]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_port = COM5
monitor_speed = 115200
board_build.psram_type = octal
board_build.psram = true
build_src_filter = +<main/main.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2
	fraunhofer-ims/AIfES for Arduino@^2.2.0



[env:ecdh]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_port = COM6
monitor_speed = 115200
board_build.psram_type = octal
board_build.psram = true
build_src_filter = +<ECDH/ecdh.cpp>
lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
	fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:ecdh_speed]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_port = COM6
monitor_speed = 115200
board_build.psram_type = octal
board_build.psram = true
build_src_filter = +<ECDH_SPEED/ecdh_speed.cpp>
lib_deps = 
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2
	fraunhofer-ims/AIfES for Arduino@^2.2.0


[env:ecdh_speed_v2]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_port = COM6
monitor_speed = 115200
board_build.psram_type = octal
board_build.psram = true
build_src_filter = +<ECDH_SPEED_v2/ecdh_speed_v2.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2
	fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:ec]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_port = COM6
monitor_speed = 115200
board_build.psram_type = octal
board_build.psram = true
build_src_filter = +<EC/try_auth.cpp>
lib_deps = fraunhofer-ims/AIfES for Arduino@^2.2.0


[env:1_federated_wifi_train]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_speed = 115200
board_build.psram_type = octal
board_build.psram = true
build_src_filter = +<1_federated_wifi_train/1_federated_wifi_train.cpp>
build_flags =
  -D CONFIG_ARDUINO_LOOP_STACK_SIZE=32768
lib_deps = fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:2_federated_wifi_train]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_speed = 115200
board_build.psram_type = octal
board_build.psram = true
build_src_filter = +<2_federated_wifi_train/2_federated_wifi_train.cpp>
build_flags =
  -D CONFIG_ARDUINO_LOOP_STACK_SIZE=32768
lib_deps = fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:3_federated_wifi_train]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_speed = 115200
board_build.psram_type = octal
board_build.psram = true
build_src_filter = +<3_federated_wifi_train/3_federated_wifi_train.cpp>
build_flags =
  -D CONFIG_ARDUINO_LOOP_STACK_SIZE=32768
lib_deps = fraunhofer-ims/AIfES for Arduino@^2.2.0

[env:4_federated_wifi_train]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_speed = 115200
board_build.psram_type = octal
board_build.psram = true
build_src_filter = +<1_federated_wifi_train/1_federated_wifi_train.cpp>
build_flags =
  -D CONFIG_ARDUINO_LOOP_STACK_SIZE=32768
lib_deps = fraunhofer-ims/AIfES for Arduino@^2.2.0


[env:federated_test]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_port = COM6
monitor_speed = 115200
board_build.psram_type = octal
board_build.psram = true
build_src_filter = +<federated_test/federated_test.cpp>
build_flags =
  -D CONFIG_ARDUINO_LOOP_STACK_SIZE=32768
lib_deps = fraunhofer-ims/AIfES for Arduino@^2.2.0


; ++++++++++++++++++++++++++++++++++++


[common_base]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
board_build.psram_type = octal
board_build.psram = true
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:present]
extends = common_base
build_src_filter = +<present/present.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:speck]
extends = common_base
build_src_filter = +<speck/speck.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:simon]
extends = common_base
build_src_filter = +<simon/simon.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:flash_present]
extends = common_base
build_src_filter = +<ROM_FLASH/flash_present.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:ram_present]
extends = common_base
build_src_filter = +<RAM/ram_present.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:speed_present]
extends = common_base
build_src_filter = +<speed/speed_present.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2


[env:flash_simon]
extends = common_base
build_src_filter = +<ROM_FLASH/flash_simon.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:ram_simon]
extends = common_base
build_src_filter = +<RAM/ram_simon.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:speed_simon]
extends = common_base
build_src_filter = +<speed/speed_simon.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:speed_speck]
extends = common_base
build_src_filter = +<speed/speed_speck.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:flash_speck]
extends = common_base
build_src_filter = +<ROM_FLASH/flash_speck.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:ram_speck]
extends = common_base
build_src_filter = +<RAM/ram_speck.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2

[env:model_inference]
extends = common_base
board_build.filesystem = spiffs
board_build.filesystem_size = 5MB
build_src_filter = +<model_inference/model_inference.cpp>
lib_deps = 
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2


